新增 TwitCasting 訂閱源
Sora233/DDBOT pull request #106
Opened 2021-12-13 12:17 UTC by eric2788

2021-12-13 16:55 UTC, eric2788 commented
啊想起來了 我是不是要 用 develop 改 merge develop branch 😃……

2021-12-14 03:02 UTC, Sora233 commented
target branch请指定develop

2021-12-14 03:02 UTC, Sora233 commented
另外订阅所使用的id是什么呢？

2021-12-14 03:06 UTC, Sora233 requested changes

2021-12-14 03:06 UTC, Sora233 commented on lsp/twitcasting/concern.go
> +	return concern.NewIdentity(id, id.(string)), nil
是否可以展示目标实际的名字，而非id呢？
如果命令反馈中没有名字，就不知道是否订阅了错误的目标了

2021-12-14 03:20 UTC, eric2788 commented on bot.go
> +# 参阅 https://apiv2-doc.twitcasting.tv/#registration
> 另外订阅所使用的id是什么呢？

twitcasting 的 screen id

2021-12-14 03:24 UTC, eric2788 commented on lsp/twitcasting/concern.go
> +	lastStatus := make(map[string]bool)
我是覺得重啟的時候重新推送一次會比較好？不過也不是不行

2021-12-14 03:26 UTC, eric2788 commented on lsp/twitcasting/concern.go
> +	return concern.NewIdentity(id, id.(string)), nil
可以，但需要請求一次 user, 這個直接用快取存，應該不用存到db吧？

2021-12-14 03:27 UTC, eric2788 commented
由於分支錯了，所以我之後會重開一個 PR，但這裏的寫的東西還有用，我要參考一下，等我重開的時候會關掉這個

2021-12-14 03:29 UTC, eric2788 commented on bot.go
> +# 参阅 https://apiv2-doc.twitcasting.tv/#registration
> 请确保没有配置的情况下可以正常运行bot

可以，只是會啟動不了 twitcasting 的 Concern 模塊

2021-12-14 06:27 UTC, Sora233 commented on lsp/twitcasting/concern.go
> +	return concern.NewIdentity(id, id.(string)), nil
> 可以，但需要請求一次 user, 這個直接用快取存，應該不用存到db吧？

可以存也可以请求，看网站是不是对请求频率有严格限制

2021-12-14 06:32 UTC, eric2788 commented on lsp/twitcasting/concern.go
> +	return concern.NewIdentity(id, id.(string)), nil
每分鐘60次，以目前ddbot間隔請求是沒啥問題，但我還是加個快取吧

2021-12-14 06:57 UTC, eric2788 commented
@Sora233 buntdb SetJson 支不支援 帶有 冒號的 key?

2021-12-14 07:06 UTC, Sora233 commented
> @Sora233 buntdb SetJson 支不支援 帶有 冒號的 key?

目前不支持，冒号是我考虑上的失误，没有想到它会比较常用，我会想办法解决一下

2021-12-14 07:09 UTC, eric2788 commented
> > @Sora233 buntdb SetJson 支不支援 帶有 冒號的 key?
> 
> 目前不支持，冒号是我考虑上的失误，没有想到它会比较常用，我会想办法解决一下

了解，那我先做個轉換

2021-12-14 07:11 UTC, Sora233 commented
> > > @Sora233 buntdb SetJson 支不支援 帶有 冒號的 key?
> > 
> > 
> > 目前不支持，冒号是我考虑上的失误，没有想到它会比较常用，我会想办法解决一下
> 
> 了解，那我先做個轉換

具体来说，是`ParseConcernStateKeyWithString`，`ParseConcernStateKeyWithInt64` 不支持解析有多个`:`的key，其他情况下自行使用是没问题的

2021-12-14 07:38 UTC, eric2788 commented
> > > > @Sora233 buntdb SetJson 支不支援 帶有 冒號的 key?
> > > 
> > > 
> > > 目前不支持，冒号是我考虑上的失误，没有想到它会比较常用，我会想办法解决一下
> > 
> > 
> > 了解，那我先做個轉換
> 
> 具体来说，是`ParseConcernStateKeyWithString`，`ParseConcernStateKeyWithInt64` 不支持解析有多个`:`的key，也就是id中不能含有`:`，其他情况下自行使用是没问题的

@Sora233 了解，另外我調用了 RemoveAllById 之後發現依然有數據存在，我該如何透過 id 移除 json 數據?

2021-12-14 07:44 UTC, closed without merging

2021-12-14 07:44 UTC, eric2788 commented
#107